/*
 * This source file was generated by the Gradle 'init' task
 */
package org.yuqu;

public class Main {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Main().getGreeting());
    }
}
